<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
        <TargetFrameworks>net9.0-android;net9.0-ios</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Vamoriq.Models\Vamoriq.Models.csproj" />
		<ProjectReference Include="..\Vamoriq.Services\Vamoriq.Services.csproj" />
	</ItemGroup>

</Project> 